export const products = [
    {
        id: 1,
        name: "Red dead Redemption 2",
        price: 110,
        description: "Experience the epic tale of outlaw Arthur Morgan and the Van der Linde gang as they navigate the decline of the Wild West in this immersive open-world adventure.",
        image: "images/products/RDR2.png",
        type: 'RPG',
        quantity: 0,
    },
    {
        id: 2,
        name: "The Witcher 3",
        price: 120,
        description: "Step into the shoes of Geralt of Rivia, a monster hunter known as a Witcher, as you explore a vast fantasy world filled with rich storytelling, complex characters, and thrilling combat.",
        image: "images/products/Witcher3.png",
        type: 'RPG',
        quantity: 0,
    },
    {
        id: 3,
        name: "Cyberpunk 2077",
        price: 200,
        description: "Dive into the neon-lit streets of Night City, a sprawling metropolis where you play as V, a mercenary outlaw on a quest for a one-of-a-kind implant that promises immortality.",
        image: "images/products/Cyberpunk2077.png",
        type: 'RPG',
        quantity: 0,
    },
    {
        id: 4,
        name: "Terraria",
        price: 25,
        description: "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. The world is your canvas and the ground itself is your paint.",
        image: "images/products/Terraria.webp",
        type: 'RPG',
        quantity: 0,
    },
    {
        id: 5,
        name: "Dark Souls III",
        price: 150,
        description: "Embark on an epic dark fantasy adventure in a world filled with fearsome enemies and challenging environments. Face overwhelming odds to fulfill your duty and rekindle the First Flame.",
        image: "images/products/DarkSouls.webp",
        type: 'soulslike',
        quantity: 0,
    },
    {
        id: 6,
        name: "Ghost of Tsushima",
        price: 180,
        description: "In the late 13th century, the Mongol empire has laid waste to entire nations. Become Jin Sakai, a samurai warrior fighting to protect his homeland on the island of Tsushima.",
        image: "images/products/GhostOfTsushima.jpg",
        type: 'Adventure',
        quantity: 0,
    },
    {
        id: 7,
        name: "Sea of Thieves",
        price: 170,
        description: "Embark on a shared-world adventure and become a pirate legend in this action-adventure game. Sail the seas, hunt for treasure, and engage in epic ship battles.",
        image: "images/products/SeaOfThieves.webp",
        type: 'Adventure',
        quantity: 0,
    },
    {
        id: 8,
        name: "Hollow Knight",
        price: 45,
        description: "Forge your own path in an epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs.",
        image: "images/products/HollowKnight.jpg",
        type: 'soulslike',
        quantity: 0,
    },
    {
        id: 9,
        name: "Sanabi",
        price: 30,
        description: "A cyberpunk action-platformer where you play as a retired veteran who must use their trusty harpoon and grappling hook abilities to explore a towering city and uncover its dark secrets.",
        image: "images/products/Sanabi.jpg",
        type: 'Adventure',
        quantity: 0,
    },
    {
        id: 10,
        name: "Sekiro: Shadows Die Twice",
        price: 160,
        description: "Carve your own clever path to vengeance in this award-winning action-adventure. Take revenge. Restore your honor. Kill ingeniously.",
        image: "images/products/Sekiro.jpg",
        type: 'soulslike',
        quantity: 0,
    },

    {
        id: 11,
        name: "Elden Ring",
        price: 120,
        description: "Step into a vast world of adventure in Elden Ring, where you can explore majestic landscapes, face formidable foes, and uncover the mysteries of the Lands Between in this critically acclaimed action RPG.",
        image: "images/products/EldenRing.png",
        type: 'soulslike',
        quantity: 0,
    },

    {
        id: 12,
        name: "zelda breath of the wild",
        price: 130,
        description: "Step into a vast open world filled with adventure, mystery, and danger in The Legend of Zelda: Breath of the Wild. Explore the kingdom of Hyrule, solve puzzles, and battle formidable foes as you embark on a quest to save Princess Zelda and defeat the evil Calamity Ganon.",
        image: "images/products/zelda.png",
        type: 'Adventure',
        quantity: 0,
    },

    {
        id: 13,
        name: "Super Mario Odyssey",
        price: 140,
        description: "Join Mario on a globe-trotting adventure in Super Mario Odyssey! Explore vibrant kingdoms, collect Power Moons, and use Mario's new friend Cappy to capture and control objects and enemies in this critically acclaimed platformer.",
        image: "images/products/mario.webp",
        type: 'Adventure',
        quantity: 0,
    },


    {
        id: 14,
        name: "Ghost runner",
        price: 50,
        description: "Become a one-armed cybernetic ninja in a post-apocalyptic world, using your agility and combat skills to navigate through a towering city and take down enemies in this fast-paced action-platformer.",
        image: "images/products/GhostRunner.png",
        type: 'Adventure',
        quantity: 0,
    },


    {
        id: 15,
        name: "Cuphead",
        price: 35,
        description: "Embark on a challenging run-and-gun adventure in Cuphead, where you play as Cuphead and Mugman, battling through a series of unique and visually stunning boss fights to repay your debt to the devil.",
        image: "images/products/Cuphead.png",
        type: 'Adventure',
        quantity: 0,
    },


    {
        id: 16,
        name: "Celeste",
        price: 40,
        description: "Join Madeline on her journey to the top of Celeste Mountain in this critically acclaimed platformer. Overcome challenging obstacles, confront your inner demons, and discover the true meaning of perseverance.",
        image: "images/products/Celeste.png",
        type: 'Adventure',
        quantity: 0,
    }
];
